
[common]

	#Properties relating to grenades
	[common.grenades]
		#The max distance which the explosion is effective to
		#Range: 0.0 ~ 1.7976931348623157E308
		explosionRadius = 2.0

	#Properties relating to stun grenades
	[common.stun_grenades]

		#Blinding properties of stun grenades
		[common.stun_grenades.blind]
			#If true, hostile mobs will be unable to target entities while they are blinded by a stun grenade.
			blindMobs = true

			[common.stun_grenades.blind.effect_criteria]
				#Effect will have this duration (in ticks) if the grenade is directly at the player's eyes while looking directly at it.
				#Range: > 0
				durationMax = 220
				#Angle between the eye/looking direction and the eye/grenade direction must be no more than half this many degrees to have an effect.
				#Range: 0.0 ~ 360.0
				angleEffect = 170.0
				#If true, the effect is only applied if the line between the eyes and the grenade does not intersect any non-liquid blocks with an opacity greater than 0.
				raytraceOpaqueBlocks = true
				#Grenade must be no more than this many meters away to have an effect.
				#Range: 0.0 ~ 1.7976931348623157E308
				radius = 15.0
				#After duration is attenuated by distance, it will be further attenuated depending on the angle (in degrees) between the eye/looking direction and the eye/grenade direction. This is done by multiplying it by 1 (no attenuation) if the angle is 0; and by this value if the angle is the maximum within the angle of effect.
				#Range: 0.0 ~ 1.0
				angleAttenuationMax = 0.75
				#Effect will have this duration (in ticks) if the grenade is the maximum distance from the player's eyes while looking directly at it.
				#Range: > 0
				durationMin = 10

		#Deafening properties of stun grenades
		[common.stun_grenades.deafen]
			#If true, peaceful mobs will panic upon being deafened by a stun grenade.
			panicMobs = true

			[common.stun_grenades.deafen.effect_criteria]
				#Effect will have this duration (in ticks) if the grenade is directly at the player's eyes while looking directly at it.
				#Range: > 0
				durationMax = 280
				#Angle between the eye/looking direction and the eye/grenade direction must be no more than half this many degrees to have an effect.
				#Range: 0.0 ~ 360.0
				angleEffect = 360.0
				#If true, the effect is only applied if the line between the eyes and the grenade does not intersect any non-liquid blocks with an opacity greater than 0.
				raytraceOpaqueBlocks = false
				#Grenade must be no more than this many meters away to have an effect.
				#Range: 0.0 ~ 1.7976931348623157E308
				radius = 15.0
				#After duration is attenuated by distance, it will be further attenuated depending on the angle (in degrees) between the eye/looking direction and the eye/grenade direction. This is done by multiplying it by 1 (no attenuation) if the angle is 0; and by this value if the angle is the maximum within the angle of effect.
				#Range: 0.0 ~ 1.0
				angleAttenuationMax = 0.75
				#Effect will have this duration (in ticks) if the grenade is the maximum distance from the player's eyes while looking directly at it.
				#Range: > 0
				durationMin = 100

	#Development
	[common.development]
		#If enabled any crosshair will continue to render on aim.
		permanentCrosshair = false
		#If enabled, /t dev will both be registered (Upon restart), and function! Used as well to speed up tag checks
		enableTDev = false
		#Whether the shooters bullets can harm the shooter, great for testing armor and on hit effects with the development gun
		bulletSelfHarm = false
		#Directory to build all TaC sub-directories, these will contain export data from /t dev functions
		tDevPath = ""

	#Properties relating to mob aggression
	[common.aggro_mobs]
		#If true, in addition to causing peaceful mobs to panic, firing a gun will also cause nearby hostile mobs to target the shooter.
		angerHostileMobs = true
		#Any mobs of defined will not aggro on shooters
		exemptMobs = []
		#Any mobs within a sphere of this radius will aggro on the shooter of an unsilenced gun.
		#Range: 0.0 ~ 1.7976931348623157E308
		unsilencedRange = 20.0
		#If true, nearby mobs are angered and/or scared by the firing of guns.
		enabled = true

	#Properties relating to missiles (no use now)
	[common.missiles]
		#The max distance which the explosion is effective to
		#Range: 0.0 ~ 1.7976931348623157E308
		explosionRadius = 1.0

	#Properties relating to projectile spread
	[common.projectile_spread]
		#Weapon grows more inaccurate depending if the player is in motion (Forward, Strafing, Jumping)
		movementInaccuracy = true

	#Properties relating to gameplay
	[common.gameplay]
		#Force camera shake on for all players, since control over the weapon is reduced with this off, having a client only options could lead to balance issues.
		forceCameraShakeOnFire = false
		#Enables the check for head shots for players. Projectiles that hit the head of a player will have increased damage.
		enableHeadShots = true
		#If enable, Fire Starter will cause fire (ignite the block)
		fireStarterCauseFire = false
		#If enable, allows guns to shoot out glass
		enableGunGriefing = true
		#The value to multiply the damage by if projectile hit the players head
		#Range: 1.0 ~ 1.7976931348623157E308
		headShotDamageMultiplier = 2.0
		#If true, improves the accuracy of weapons by considering the ping of the player. This has no affect on singleplayer. This will add a little overhead if enabled.
		improvedHitboxes = true
		#True if you want to see the laser beam from a third-person perspective.
		canSeeLaserThirdSight = true
		#Enable rendering of TaC armor on the player, useful if other armors are taking priority, doesn't fit gameplay theme, or not performant enough.
		renderTaCArmor = true
		#Bullets completely ignore Minecraft armor, forcing you to use our armor system.
		bulletsIgnoreStandardArmor = true
		#True if you don't want pack up the item on your left hand, this option will keep the item but unable to use it and stop render it.
		bannedDrop = true
		#Iron sights fov modification will not affect the players fov at all
		realisticIronSightFovHandling = false
		#True if you don't want to hurt players.
		gunOfKindnessToPlayer = false
		#If enable, allows guns to remove blocks on explosions
		enableExplosionBreak = false
		#If true, projectiles will cause knockback when an entity is hit. By default this is set to true to match the behaviour of Minecraft.
		enableKnockback = true
		#The percent of the damage ignore the armor, 0 = Minecraft armor effectiveness doesn't change, 1 = Minecraft armor never effects bullet damage.
		#Range: 0.0 ~ 1.0
		percentDamageIgnoresStandardArmor = 0.5
		#If enable, explosion will cause fire (ignite the block)
		explosionCauseFire = false
		#Enables the safe mode on weapons, false completely nullifies the existence of the safety
		safetyExistence = false
		#True if you don't want to hurt any mobs.
		gunOfKindness = false
		#If true, projectiles will ignore leaves when checking for collision
		ignoreLeaves = true
		#Optics with 0 fov modification will not affect the players fov at all
		realisticLowPowerFovHandling = false
		#The extra amount to expand an entity's bounding box when checking for projectile collision. Setting this value higher will make it easier to hit entities
		#Range: 0.0 ~ 1.0
		growBoundingBoxAmountV2 = 0.0
		#All weapons have a percentage of damage applied, no matter the class match up, false means blunt damage is never applied before armor calc.
		armorBluntDamage = true
		#The value to multiply the damage by if projectile is a critical hit
		#Range: 1.0 ~ 1.7976931348623157E308
		criticalDamageMultiplier = 2.0
		#Sets the strength of knockback when shot by a bullet projectile. Knockback must be enabled for this to take effect. If value is equal to zero, knockback will use default minecraft value
		#Range: 0.0 ~ 1.0
		knockbackStrength = 0.15
		#Aiming will present a breathing animation, moving the weapon over time, crouch to lower it's effects
		realisticAimedBreathing = false

	#Properties relating to network
	[common.network]
		#The distance players need to be within to be able to track new projectiles trails. Higher values means you can see projectiles from that start from further away.
		#Range: 1.0 ~ 1.7976931348623157E308
		projectileTrackingRange = 200.0

